#!/usr/bin/env python
import pandas as pd
import joblib
from sklearn.linear_model import LinearRegression

# import training data
X_train = pd.read_csv('/opt/ml/input/data/train/X_train.csv')
y_train = pd.read_csv('/opt/ml/input/data/train/y_train.csv')

def train():
    # train the LinearRegression model
    linear_model = LinearRegression()
    linear_model.fit(X_train, y_train)
    
    # Pickle trained LinearRegression model
    joblib_file = "/opt/ml/model/lr_model.pkl"
    joblib.dump(linear_model, joblib_file)
    
if __name__ == "__main__":
    train()